### PR TITLE
Migrate null safety

### PR DESCRIPTION
**Pull request by acoutts**
This PR migrate all of the `http_extensions` libs to null safety. First the `http_extensions` lib needs to be published as version `1.0.0` and all of the deps here will work.

To test this before `http_extensions 1.0.0` is published, you need this override:
```yaml
dependency_overrides:
 http_extensions: 
  git:
    url: https://github.com/bottlepay/http_extensions.git
    path: http_extensions
```

### CODE REVIEW

**Comment by river-littlepay** [comment]
Not familiar with this plugin but `stores/memory_store.dart`, line 17, `Future<CachedResponse> get(String id)` also need to be update to Nullable value and it is throwing `type 'Null' is not a subtype of type 'CachedResponse' in type cast` and causing `jose` tests fail.

**Comment by acoutts** [comment]
@river-littlepay is that on my PR with jose migrated as well?

**Comment by acoutts** [comment]
https://github.com/appsup-dart/jose/pull/23

**Comment by acoutts** [comment]
@aloisdeniel any chance to review / publish this?

**Comment by aloisdeniel** [comment]
I'm going to review that today (sorry for the delay)!

Thanks a lot for the migration

**Comment by aloisdeniel** [comment]
Version 1.0.0 is now available on pub.

Thanks again ;)

**Comment by acoutts** [comment]
Thank you!

**Pull request merged**
